### ISSUE TITLE
공개 키 기반 인증

### ISSUE THREAD

**Issue by tirr-c** [bacchus-snu/id#143]
IP 기반 디바이스 인증은 구리기도 하고 상대 IP를 확인할 수 없는 환경에서는 작동하지 않으니, 공개 키 기반으로 재작성합시다.

Ed25519가 참 좋습니다. [TweetNaCl]이 C와 자바스크립트 구현체가 모두 존재하니까 이걸 씁시다.

[TweetNaCl]: http://tweetnacl.cr.yp.to/

**Comment by seojangho** [comment]
+`

**Comment by tirr-c** [comment]
8월 10일에 @soleee99 님과 함께 실습실 컴퓨터에 적용합니다.

**Comment by tirr-c** [comment]
하실/과방 컴퓨터에 적용이 끝났습니다.
