### ISSUE TITLE
학번이 없는 계정

### ISSUE THREAD

**Issue by ulgal** [bacchus-snu/id#157]
학번을 정보가 없는 계정이 교수님, 행정실 직원 및 시험용 실습 계정을 제외하고도 몇몇 있는 것 같습니다.
#56 이전에 가입했으면서 기존 스누씨2 DB에 정보가 없는 계정(#57)이라 생각하는데, 이 계정이 그룹 가입 신청을 할 경우
[getALLPendingMembershipUsers](https://github.com/bacchus-snu/id/blob/360052b96b39d38d42a76ff225b8efbb283cc228/core/src/model/users.ts#L357)의 INNER JOIN에서 student_numbers table에 정보가 없기 때문에 쿼리로 얻어오지 못합니다.

**Comment by tirr-c** [comment]
cc #254, #256
