### ISSUE TITLE
이메일 로컬 부분에 "." 이 포함되면 올바르지 않은 이메일로 리턴됨.

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [bacchus-snu/id#260]
Was on https://github.com/snucse/snucse/issues/115
# Issue description
When I was trying to signup on CSE homepage, I need to enter the snu email.
However, the system keep saying that I haven't entered the proper email address.
I have slightly investigated this and found that if the email includes "." then the system detects it as unacceptable email.

# How to reproduce
## Request
~~~bash
curl --location 'https://id.snucse.org/signup/email' \
--header 'Content-Type: application/json' \
--data-raw '{"email": "john.jongyoon.kim@snu.ac.kr"}'
~~~
## Response
~~~
{
    "message": "사용할 수 없는 이메일입니다."
}
~~~

**Comment by ArtemisDicoTiar** [comment]
https://github.com/bacchus-snu/id/blob/63f4e1b836f721492f3dd893ec2f4ee3e6874e59/src/api/email.ts#L23C2-L23C59
여기에 "." 이 regex에서 빠져야함.

**Comment by nevivurn** [comment]
Invalid, see https://github.com/bacchus-snu/id/pull/261#issuecomment-2230129772

**Comment by ArtemisDicoTiar** [comment]
@nevivurn 답변해주셔서 감사합니다.
비밀번호 재설정후 다시 로그인을 시도했으나 이러한 warning을 프론트 단에서 보여주고 있습니다.
프론트의 문제인가요?
<img width="397" alt="Screenshot 2024-07-22 at 4 50 48 PM" src="https://github.com/user-attachments/assets/a7679a68-45aa-4380-a5b6-7edc4a9967a4">

**Comment by nevivurn** [comment]
> @nevivurn 답변해주셔서 감사합니다. 비밀번호 재설정후 다시 로그인을 시도했으나 이러한 warning을 프론트 단에서 보여주고 있습니다. 프론트의 문제인가요?

username 필드에는 이메일 말고 사용자명을 입력해주시기 바립니다.
계정 관련 문의는 학내 이메일 (`@snu.ac.kr`)에서 <contact@bacchus.snucse.org>으로 보내주시기 바랍니다.
