### ISSUE TITLE
ldap 사이드 마무리

### ISSUE THREAD

**Issue by seojangho** [bacchus-snu/id#39]
* [ ] 로그인을 시도한 유저만 uid가 assign되도록 고치기
* [ ] ldap posixGroup 추가

**Comment by skystar-p** [comment]
STARTTLS는 구현이 간단할까요? 실습실 컴퓨터하고 잘 통신하나 실험이 필요한 상태입니다.

**Comment by skystar-p** [comment]
뭔가 혼자서 잘 할 것 같은데 한번 테스트를 해봐야겠습니다 (...)
