### ISSUE TITLE
신규 가입 Pending users로 빼서 승인 절차 거치기

### ISSUE THREAD

**Issue by skystar-p** [bacchus-snu/id#46]
현재 snu메일을 가지고 있는 사람들은 모두 가입이 가능한데, 회원가입을 승인식으로 바꾸어야 합니다.

한 학기만 지속되는 실습계정은 어떻게 할지는 더 생각해봐야 할 것 같습니다.

**Comment by tirr-c** [comment]
5년 가까이 이대로 지냈으니 아마 괜찮을듯
