### ISSUE TITLE
이메일 sanitation

### ISSUE THREAD

**Issue by likcoras** [bacchus-snu/id#51]
현재 `emailDomain === "snu.ac.kr"` 외에 이메일 sanitation이 없어서 "emailLocal=address@example.com, <anything>&emailDomain=snu.ac.kr"를 보내면 계정을 여러 개 만들거나 동시에 이메일을 여러 개 보내거나 할 수 있습니다.

그리고, 이메일은 case-insensitive 하므로 "example@example.com"이랑 "eXample@example.com"은 둘 다 똑같은 이메일이지만 가입은 여러 번 할 수 있는 것도 막아야 합니다.

`[a-zA-Z0-9-_\.]` 필터링 + normalization (`toLower()` ?) 하면 될 것 같습니다.

**Comment by skystar-p** [comment]
그런데 `emailLocal=address@example.com&emailDomain=snu.ac.kr` 이면 어차피 메일이 안보내지니까 상관 없을 것 같습니다. `toLowerCase()`를 적용하는건 나쁘지 않아 보이네요.

**Comment by 81887821** [comment]
https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive#9808332
메일 서버에 따라 case-sensitive할 수도 있다고 합니다

**Comment by 81887821** [comment]
메일을 보낼 때와 DB에 저장할 때는 사용자가 입력한 그대로의, 대소문자를 구분하는 값으로 저장하고, 새로 사용자가 가입할 때 대소문자를 구분하지 않고 중복 체크를 하는 것이 최선이지 않을까 싶습니다

**Comment by likcoras** [comment]
앗 잘못 썼는데 "emailLocal=address@example.com, any-email"로 보내면 NodeMailer이 "To: address@example.com, any-email@snu.ac.kr"로 이메일을 여러 개 보내줍니다.

![2018-09-02-203248_1365x247_scrot](https://user-images.githubusercontent.com/7698349/44955526-af85d300-aeef-11e8-8240-5c2c309b601c.png)

> 메일을 보낼 때와 DB에 저장할 때는 사용자가 입력한 그대로의, 대소문자를 구분하는 값으로 저장하고, 새로 사용자가 가입할 때 대소문자를 구분하지 않고 중복 체크를 하는 것이 최선이지 않을까 싶습니다

`create unique index email_addresses_lower_idx on email_addresses (LOWER(address_local), address_domain)`식으로 하는거 맞나요?

**Comment by skystar-p** [comment]
오 그런 방법이... 그렇다면 지금 있는 regexp는 꼭 필요하네요

그리고 아마... 저 위의 unique constraint는 문법 오류가 날텐데 field를 `citext`로 하든가 (extension 필요)

아니면 `create unique index` 문을 사용해야 할 것 같아요.

**Comment by skystar-p** [comment]
Closed by #53
