### ISSUE TITLE
어드민 페이지 만들기

### ISSUE THREAD

**Issue by nevivurn** [bacchus-snu/id#88]
그룹에 가입신청하면 그룹 관리자가 승인해주는 페이지, 최소한 ID에 가입신청한 사람들 정보를 볼 수 있고 승인해줄 수 있는 페이지

이거 관리해줄 API endpoint들도 만들어야 합니다.

**Comment by ryul99** [comment]
어드민페이지는 그룹장이 개개인을 선택해서 그룹에 추가하는 형식이 아닌 개개인이 그룹에 신청하고 그룹장이 이를 승락하는 구조로 만들기로 결정했습니다.

**Comment by nevivurn** [comment]
Front:
- 그룹 목록
  - 그룹마다 신청 status (신청중, 가입)
  - 그룹마다 안내메시지 ("컴공 (부)전공자들만", "어떠어떠한 수업 수강생들만", etc.)
  - 자신이 속해있지 않고 아직 가입신청하지 않은 그룹에는 가입신청을 보낼 수 있다
- 그룹장은 자신이 어떤 그룹의 그룹장이라는걸 볼 수 있게 한다
- 그룹 신청인 목록
  - 자신이 그룹장인 그룹에 가입신청한 사용자들 목록
  - 이름, 학번 표기
  - 승인/거부할 수 있다.

API:
- 그룹 목록
  - owner != null인 그룹들만 돌려준다 (신청가능 그룹)
  - 이 요청을 날린 사용자의 membership status도 돌려준다
- 그룹 신청인 목록
  - 그룹장만 볼 수 있다
  - 각 사용자의 이름과 학번을 돌려준다
- 그룹 가입신청 / 승인 / 거부

그리고 생각해보니 그룹 멤버 목록 + 이미 가입한 사용자를 없엘 수 있는 방법도 있어야 할 것 같습니다 (드랍 등). 그룹장만 볼 수 있는 신청인 목록이랑 같이 보내고 status같은걸로 구분하고 kick는 신청 거부랑 동일한 요청으로 처리하면 될 것 같습니다.
